### ISSUE TITLE
[bug]: Quick Search Style

### ISSUE THREAD

**Issue by Agility6** [toeverything/AFFiNE#645] opened 2023-01-01 09:07 UTC
### Describe the bug

Wrong ctrl + K style for search

### To Reproduce

1. https://pathfinder.affine.pro/
2. Ctrl + K

### Screenshots

![Snipaste_2023-01-01_17-06-53](https://user-images.githubusercontent.com/75616395/210165845-a71f2d98-d257-40b3-a6c7-5e148759f09f.png)

### Platform

Window11

### Browser

Chrome

**Comment by tzhangchi** [comment] 2023-01-01 15:28
@Agility6 Thank you for your bug report ,now this issue will be fixed by @JimmFly

**Comment by JimmFly** [comment] 2023-01-01 15:48
@Agility6 Could you please tell me your screen resolution?

**Comment by Agility6** [comment] 2023-01-01 15:53
@JimmFly Hello! 2560*1440

**Comment by JimmFly** [comment] 2023-01-01 16:09
> @JimmFly Hello! 2560*1440

Sorry for the late reply, I can't reproduce the error at the moment, but I'm guessing it might have something to do with your zoom level. Can you post a screenshot of the full page or a video of the operation to reproduce the bug? This might be of some help to me.

**Comment by Agility6** [comment] 2023-01-01 16:21
> > @JimmFly Hello! 2560*1440
> 
> Sorry for the late reply, I can't reproduce the error at the moment, but I'm guessing it might have something to do with your zoom level. Can you post a screenshot of the full page or a video of the operation to reproduce the bug? This might be of some help to me.

Has this problem been solved?
https://user-images.githubusercontent.com/75616395/210177697-68b5a314-d6fa-40ca-a2d8-f5c9c014afa8.mp4

**Closed** 2023-01-01 16:21 UTC
Labels: bug, alpha, triaging

**Comment by JimmFly** [comment] 2023-01-01 16:41
> Has this problem been solved? 

Thanks again for your bug report, I think this PR will fix this bug and it will work in the next update.
