### ISSUE TITLE
Signing error page during the process of accepting invitation of join workspace

### ISSUE THREAD

**Issue by xell** [toeverything/AFFiNE#4177] opened 2023-09-05 01:52 UTC
Steps in https://insider.affine.pro :

1.  Clicking the invitation link in the "Invitation to workspace" email.
2. Using Sign in with Google to sign.
3. After successfully logging in, I got the following screenshot:

![CleanShot 2023-09-05 at 09 45 06@2x](https://github.com/toeverything/AFFiNE/assets/132558/5a146688-50c8-4840-ba83-c5d5b9359bf2)

4. However, I can paste the invitation URL ( `http://insider.affine.pro/invite/XXX` ) in the browser to open it again, and it went well to the "Successfully joined" page:

 
![CleanShot 2023-09-05 at 09 45 33@2x](https://github.com/toeverything/AFFiNE/assets/132558/dbdf729e-a69c-4ce4-aef1-61aabfd1a00f)

**Comment by Brooooooklyn** [comment] 2023-09-05 06:17
I can't reproduce it, maybe you are opening a link that was sent by the buggy version of server, this should be fixed now.

**Closed** 2023-09-06 17:15 UTC
Labels: type:bug, fatal, mod:share
