### ISSUE TITLE
Cursor focus lost after adding a to-do item​

### ISSUE THREAD

**Issue by kemalakcc** [toeverything/AFFiNE#4977] opened 2023-11-17 11:31 UTC
### What happened?

Below, I'm trying to add a to-do item without using mouse. After adding an item, cursor focus is getting lost so I need to click with mouse to continue writing

![Peek 2023-11-17 14-27](https://github.com/toeverything/AFFiNE/assets/117591520/7844cffe-045d-43f0-8fba-18b53b0c137a)

### Distribution version

Web (insider.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Firefox

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SuyashOP-2** [comment] 2023-11-24 05:03
It is working fine

**Comment by SuyashOP-2** [comment] 2023-11-24 05:04
It is working fine 🙂

**Comment by kmlkcl** [comment] 2023-11-24 13:56
what do you mean by that? Working fine?

**Comment by EYHN** [comment] 2023-11-25 02:40
I've reproduced the issue but I haven't had time to investigate the cause yet, it would be great if anyone would help.

**Comment by deadland2002** [comment] 2023-11-26 11:36
I can try

**Comment by EYHN** [comment] 2023-11-27 04:29
@deadland2002 Give it a try and ask here if you have any questions.

**Comment by EYHN** [comment] 2023-11-28 10:31
Looks like it's been fixed in 0.10.2

**Closed by EYHN** 2023-11-28 10:31 UTC
Labels: type:bug, good first issue, help wanted
