### ISSUE TITLE
​Mac German keyboard typing "ß" switches between edgeless and paged mode  

### ISSUE THREAD

**Issue by antoniozh** [toeverything/AFFiNE#4793] opened 2023-10-31 16:12 UTC
### What happened?

When I am in the editor and try to type the letter "ß", Affine switches between edgeless and paged mode and does not enter the key instead. I can't seem to find the hotkey in the hotkey settings so I can't disable it either.
This does not happen in the demo online. Is this intended hotkey behaviour and if yes, can there be an option to disable/change it?

### Distribution version

macOS ARM 64 (Apple Silicon)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment] 2023-11-01 14:42
Hi, Zhu. This issue looks interesting. I have investigated the cause of this issue, the code doesn't account for the German keyboard.

and i've submitted a PR to fix this issue.
https://github.com/toeverything/AFFiNE/pull/4813.

**Comment by lawvs** [comment] 2023-11-02 07:50
Fixed in https://github.com/toeverything/AFFiNE/pull/4813, thanks to the efforts of @EYHN

**Closed by lawvs** 2023-11-02 07:50 UTC
Labels: type:bug
