### ISSUE TITLE
Table View Ordering Rows with Drag & Drop [Edgeless Mode]​

### ISSUE THREAD

**Issue by kemalakcc** [toeverything/AFFiNE#4853] opened 2023-11-06 20:58 UTC
### What happened?

It works correctly and very smoothly on paper mode, but if you're in edgeless, everything goes crazy.

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment] 2023-11-07 08:11
Hi kemal 👋

I tried the table view in edgeless mode on my computer and couldn't reproduce the situation you described.

Could you please provide a screen recording demonstrating the situation you mentioned?

**Comment by kemalakcc** [comment] 2023-11-07 22:45
Hi! I tried but I couldn't 😄

**Comment by EYHN** [comment] 2023-11-09 06:44
I think I can close this issue first. If you can reproduce it, feel free to reopen.

**Closed by EYHN** 2023-11-09 06:44 UTC
Labels: reproduction needed
