### ISSUE TITLE
Enhance OFFLINE app prefer workflow for "Cloud Synced Workspaces"

### ISSUE THREAD

**Issue by freddieentity** [toeverything/AFFiNE#6153] opened 2024-03-16 14:03 UTC
### Description

Hi team,

I have a problem when I was trying to edit my content in offline of the "already cloud synced workspace". It just automatically log out my cloud workspaces. It would be wonderful to add a function that keeps the cloud workspaces there for offline changes and continue to the current implemented approach of auto-syncing when Internet comes back.

Thank you 👯 

### Use case

Enhanced offline mode usage

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment] 2024-03-17 07:00
This is the very important thing on our roadmap, and we plan to achieve full offline availability in 0.14.

**Comment by EYHN** [comment] 2024-03-17 07:03
Since this issue is a duplicate of #5959, I will close this issue

**Closed as not planned** 2024-03-17 07:04 UTC
Labels: story
