### ISSUE TITLE
​collaborating button not functioning?

### ISSUE THREAD

**Issue by Liquefy7822** [toeverything/AFFiNE#1987] opened 2023-04-17 09:50 UTC
### What happened?

there seems to be a problem with the collaborate button on the screen. i cannot seem to press it. when I press it it ends out highlighting the text. the email I am trying to send to is an organisation email so idk if it works or not.  i tried attaching a video to see if it helps. but then I released that the email of the person is showed so if yall need it pls tell me and I will send you privately. 

### Version

macOS ARM 64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment] 2023-04-17 14:31
This is expected behavior on the desktop app. We disabled the collaboration in the desktop release because API incompatibility

**Comment by himself65** [comment] 2023-04-18 07:25
Landed in https://github.com/toeverything/AFFiNE/commit/f6fb049ff2f8b126004faec2894b165f00487057

**Closed** 2023-04-18 07:25 UTC
Labels: bug
