### ISSUE TITLE
​Can no longer sign into Affine Cloud (Self-Hosted)

### ISSUE THREAD

**Issue by n1njaznutz** [toeverything/AFFiNE#6181] opened 2024-03-18 21:24 UTC
### What happened?

Self hosting via Docker on Synology NAS. Docker update today to following version:

Affine : 0.12.0-nightly-202403180833-e9e6b64

Editor Version : 0.13.0-canary-202403140735-2367cd5

Can no longer sign into Affine Cloud (self-hosted). Enter admin email and password and won't sign in. Everything was working as expected before latest update to above versions.

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [X] Yes

### Anything else?

This is the docker compose:

version: '3.9'
services:
  affine:
    image: ghcr.io/toeverything/affine-graphql:stable
    container_name: AFFINE
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/3010' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    command:
      ['sh', '-c', 'node ./scripts/self-host-predeploy && node ./dist/index.js']
    ports:
      - 3010:3010
      - 5555:5555
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - /volume1/docker/affine/config:/root/.affine/config:rw
      - /volume1/docker/affine/storage:/root/.affine/storage:rw
    logging:
      driver: 'json-file'
      options:
        max-size: '1000m'
    restart: on-failure:5
    environment:
      - NODE_OPTIONS="--import=./scripts/register.js"
      - AFFINE_CONFIG_PATH=/root/.affine/config
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgres://affineuser:affinepass@postgres:5432/affine?sslmode=disable
      - NODE_ENV=production
      - AFFINE_ADMIN_EMAIL=*********
      - AFFINE_ADMIN_PASSWORD=*********
  redis:
    image: redis:latest
    container_name: AFFINE-REDIS
    restart: on-failure:5
    volumes:
      - /volume1/docker/affine/redis:/data:rw
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:16
    container_name: AFFINE-DB
    restart: on-failure:5
    volumes:
      - /volume1/docker/affine/db:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "affine", "-U", "affinesuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: affineuser
      POSTGRES_PASSWORD: affinepass
      POSTGRES_DB: affine
      PGDATA: /var/lib/postgresql/data/pgdata

**Comment by civilblur** [comment] 2024-03-19 00:24
I believe your situation is the same as #6120, where it is mentioned that they're working on it.

**Comment by pengx17** [comment] 2024-03-19 02:15
Duplicate of https://github.com/toeverything/AFFiNE/issues/6120. Closing.

**Closed as not planned by pengx17** 2024-03-19 02:15 UTC
