### ISSUE TITLE
​Impossible to self-host AFFiNE stable/canary

### ISSUE THREAD

**Issue by NyaomiDEV** [toeverything/AFFiNE#6154] opened 2024-03-16 21:51 UTC
### What happened?

Decided to try AFFiNE Selfhosted out, so I downloaded your compose file and brought it up. However, it cannot be brought up as the predeploy script fails with the error I am attaching below.

### Distribution version

Linux

### Are you self-hosting?

- [X] Yes

### Relevant log output

```shell
affine_selfhosted  | [Nest] 89  - 03/16/2024, 9:49:05 PM   ERROR [RunCommand] Failed to run data migration
affine_selfhosted  | [Nest] 89  - 03/16/2024, 9:49:05 PM   ERROR [RunCommand] PrismaClientKnownRequestError: 
affine_selfhosted  | Invalid `prisma.user.create()` invocation:
affine_selfhosted  | 
affine_selfhosted  | 
affine_selfhosted  | An operation failed because it depends on one or more records that were required but not found. No 'Features' record(s) (needed to inline the relation on 'UserFeatures' record(s)) was found for a nested connect on one-to-many relation 'FeaturesToUserFeatures'.
affine_selfhosted  | error Command failed with exit code 1.
affine_selfhosted  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
affine_selfhosted  | node:internal/errors:932
affine_selfhosted  |   const err = new Error(message);
affine_selfhosted  |               ^
affine_selfhosted  | 
affine_selfhosted  | Error: Command failed: yarn predeploy
affine_selfhosted  |     at checkExecSyncError (node:child_process:890:11)
affine_selfhosted  |     at execSync (node:child_process:962:15)
affine_selfhosted  |     at runPredeployScript (file:///app/scripts/self-host-predeploy.js:44:3)
affine_selfhosted  |     at file:///app/scripts/self-host-predeploy.js:52:1
affine_selfhosted  |     at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
affine_selfhosted  |     at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
affine_selfhosted  |     at async loadESM (node:internal/process/esm_loader:28:7)
affine_selfhosted  |     at async handleMainPromise (node:internal/modules/run_main:113:12) {
affine_selfhosted  |   status: 1,
affine_selfhosted  |   signal: null,
affine_selfhosted  |   output: [ null, null, null ],
affine_selfhosted  |   pid: 20,
affine_selfhosted  |   stdout: null,
affine_selfhosted  |   stderr: null
affine_selfhosted  | }
affine_selfhosted  | 
affine_selfhosted  | Node.js v20.11.1
affine_selfhosted exited with code 0
```

### Anything else?

Docker 25.0.4
Arch Linux rolling
Linux 6.7.9-arch1-1

**Comment by ovizii** [comment] 2024-03-16 22:47
Same here. I slightly adapted the compose file but nothing which should trigger this. 

Also, when I fire the stack up I see warnings, did you also get those?


```
docker compose up -d
WARN[0000] The "Td" variable is not set. Defaulting to a blank string.
WARN[0000] The "Nfa7q" variable is not set. Defaulting to a blank string.
WARN[0000] The "Td" variable is not set. Defaulting to a blank string.
WARN[0000] The "Nfa7q" variable is not set. Defaulting to a blank string.
WARN[0000] The "Td" variable is not set. Defaulting to a blank string.
WARN[0000] The "Nfa7q" variable is not set. Defaulting to a blank string.
```

**Comment by brocar** [comment] 2024-03-16 23:19
Encountered exactly the same issue.

I could fix it for now by using a old release:
```
services:
    affine:
        image: ghcr.io/toeverything/affine-graphql:stable-cd56d8a
```

You can find all available versions [here](https://github.com/toeverything/AFFiNE/pkgs/container/affine-graphql/versions?filters%5Bversion_type%5D=tagged).

**Comment by brocar** [comment] 2024-03-16 23:26
> Same here. I slightly adapted the compose file but nothing which should trigger this.
> 
> Also, when I fire the stack up I see warnings, did you also get those?
> 
> ```
> docker compose up -d
> WARN[0000] The "Td" variable is not set. Defaulting to a blank string.
> WARN[0000] The "Nfa7q" variable is not set. Defaulting to a blank string.
> WARN[0000] The "Td" variable is not set. Defaulting to a blank string.
> WARN[0000] The "Nfa7q" variable is not set. Defaulting to a blank string.
> WARN[0000] The "Td" variable is not set. Defaulting to a blank string.
> WARN[0000] The "Nfa7q" variable is not set. Defaulting to a blank string.
> ```

This can happen due to docker variable substitution if you use $ signs in your compose configuration (password?).
You can read about it [here](https://docs.docker.com/compose/compose-file/compose-file-v2/#variable-substitution).

**Comment by forehalo** [comment] 2024-03-17 03:12
It's a bug confirmed and will be fixed asap

**Comment by EYHN** [comment] 2024-03-17 06:59
Pls use the image tag with `stable-cccea3e`, until we fix this.

**Closed as completed** 2024-03-18 03:43 UTC

**Comment by EYHN** [comment] 2024-03-18 13:02
stable tag has been fixed and ready to go
