### ISSUE TITLE
Unable to copy text from a page​

### ISSUE THREAD

**Issue by JonathanHarford** [toeverything/AFFiNE#6463] opened 2024-04-05 15:40 UTC
### What happened?

When I select text from a page, I cannot copy it to my clipboard. I've tried:
* Cmd+C
* RIght-click: Copy
* Clicking the "copy" button on the popup

Every time I try to paste, instead it pastes what I had previously copied (i.e. not something from my Affine)

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Chrome, Firefox

### Are you self-hosting?

- [ ] Yes

### Relevant log output

```shell
TypeError: Cannot read properties of undefined (reading 'write')
    at l.writeToClipboard (index.ts:210:31)
    at async l.copySlice (index.ts:240:5)
```

### Anything else?

AFFiNE 0.13.4
AFFiNE Editor Version
0.14.0-canary-202403250855-4171ecd
Hosted on a machine on my local network, not app.affine.pro.

**Comment by EYHN** [comment] 2024-04-06 09:09
It is a known issue that firefox cannot copy. Please confirm again whether chrome can copy.

**Comment by JonathanHarford** [comment] 2024-04-06 20:04
Correct, unable to copy with Chrome.

https://github.com/toeverything/AFFiNE/assets/3912650/c987c2e6-044f-47cd-a794-86d1f0bb7ad8

**Comment by pengx17** [comment] 2024-04-08 06:18
Should be duplicate of https://github.com/toeverything/AFFiNE/issues/5944
You may need to serve the web page with https for self-hosting

**Comment by javix64** [comment] 2024-04-12 11:24
> Should be duplicate of #5944 You may need to serve the web page with https for self-hosting

Hey @pengx17, can you explain how to serve with https for self-hosting?

I explain myself: As far I know, you need to create a certificate (at last with let's encrypt) for deploying it with certificate, but in any place of AFFINE say or explain how to achive this.

I have searched in reddit, in the official documentation and in github, but anyway, does not appear how to do it.

I am using the docker version, but will be easier and fantastic if someone implement this feature for the future.

I think that is a must that any APP can copy & paste anything.

Thanks, I am waiting for your answer.

**Comment by medoix** [comment] 2024-05-01 21:47
I am proxying Affine behind Cloudflare using HTTPS and Copy+Paste using either the keyboard shortcuts or even mouse right click does not work still in Firefox BUT it DOES work in Chrome it seems.

I am running Affine in Docker Self Host using the Beta tag.

In Firefox i get the following
```
ReferenceError: ClipboardItem is not defined
    writeToClipboard index.ts:214
    copySlice index.ts:244
    copy index.ts:135
    E copy-selected-models.ts:41
    49962/d/this.chain/e[i]/< manager.ts:147
    e manager.ts:159
    e manager.ts:160
    L get-selected-models.ts:61
    49962/d/this.chain/e[i]/< manager.ts:147
    e manager.ts:159
    e manager.ts:160
    with manager.ts:47
    e manager.ts:159
    run manager.ts:30
    onPageCut index.ts:128
    run dispatcher.ts:143
    _cut clipboard.ts:30
    c rocket-loader.min.js:1
    ```

**Comment by KranzAklilu** [comment] 2024-05-08 00:11
this happens also for the cloud version. (also using firefox and not getting this using chrome)

**Comment by oiqm4T** [comment] 2024-06-18 15:15
any update to this issue? not able copy and paste out of Affine self hosted. -- Solved for me

It seems using HTTPS fixed the issue.

**Closed as completed** 2024-08-09 09:34 UTC
