### ISSUE TITLE
Linked pages in public page

### ISSUE THREAD

**Issue by Martsinian** [toeverything/AFFiNE#8248] opened 2024-09-13 10:31 UTC
### Description

Hello! I would like to describe an issue I’ve observed. I made one of my pages public, and this page contained links to other pages. When trying to open these links from the public page, they wouldn’t open, which makes sense because those pages hadn’t been made public yet. However, after I granted public access to these linked pages, they still wouldn’t open.

It would be great if there could be a feature that allows public pages to open links to other public pages without needing to explicitly provide the public link for each one.

Thank you in advance!

### Use case

This feature would be useful for any user who wants to create a web of interlinked public pages without the need for each page to have a separate public link. It would improve the flow and ease of navigation between public pages, especially in cases where users create complex projects with multiple linked resources.

### Anything else?

Currently, the only way to open public pages is through the public link to that specific page. However, it would be more convenient if the link would automatically work if the page is public.
<img width="327" alt="Screenshot 2024-09-13 at 12 28 09" src="https://github.com/user-attachments/assets/fb198d38-0216-451e-bcd6-94417ea40872">

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by 0-Vanes-0** [comment] 2024-09-16 09:27
Duplicate of #8015

(I can't wait for this fix, subpages are the most **_important_** feature for me)

**Comment by forehalo** [comment] 2024-09-18 04:29
closed by #8238, will be landed in 0.17.0 this week

**Closed as completed by forehalo** 2024-09-18 04:29 UTC
Labels: story
