### ISSUE TITLE
​Slash Menu stuck

### ISSUE THREAD

**Issue by dingemann** [toeverything/AFFiNE#6322] opened 2024-03-26 08:52 UTC
### What happened?

When typing "go t" the Slash-Menu and the whole app gets stuck for 30 seconds. 
Because I didn't see the "o" showing up I typed it multiple times which appeared later:
<img width="295" alt="Bildschirmfoto 2024-03-26 um 09 49 04" src="https://github.com/toeverything/AFFiNE/assets/714974/7235ec01-f4e2-4001-854c-05456e31353d">

Restarting the app gets it running again.

### Distribution version

macOS x64 (Intel)

### Are you self-hosting?

- [ ] Yes

**Comment by EYHN** [comment] 2024-03-26 12:56
Approximately how many docs are there in your workspace?

may be fixed by #6319

**Comment by dingemann** [comment] 2024-03-27 10:36
I have 25 docs in my space. 
I have three different spaces and this only happens in one of them.

**Comment by EYHN** [comment] 2024-03-27 13:32
Sorry, I can't reproduce this issue.

The performance of the affine app seems to have slowed down a bit recently, I'm going to deploy some optimizations and let's see if is improvement.

**Comment by dingemann** [comment] 2024-03-27 16:52
It seems to be workspace-specific and only happening on one of my workspaces. I can reproduce it consistently. Is there anything I can provide you with, that could help?

**Comment by EYHN** [comment] 2024-03-28 08:35
Thanks, it would be very helpful if you can record a CPU profile.

You can follow my screen recording:

https://github.com/toeverything/AFFiNE/assets/13579374/44547412-0350-482b-8242-3a7d274c6d55

**Comment by dingemann** [comment] 2024-03-28 17:20
Amazing Screen Recording 🤩
Attached you find the CPU profile.
[Trace-20240328T181926.json](https://github.com/toeverything/AFFiNE/files/14793353/Trace-20240328T181926.json)

**Comment by pengx17** [comment] 2024-03-29 07:58
By looking at the cpu profile, it looks to me to be related to https://github.com/pacocoursey/cmdk/blob/v0.2.1/cmdk/src/command-score.ts#L81C3-L144C4

**Comment by dingemann** [comment] 2024-03-29 15:31
Great you could find something related @pengx17 . I'm not a programmer, so I can't comment on that part 😅 I'll leave it to you. lmk if you need anything else from me.

**Comment by dingemann** [comment] 2024-05-16 17:00
@pengx17 could you already find a solution to the stuck cmdk menu? Currently I cannot use the search function anymore, which is quite tiresome in a bigger space. 
I already exported an imported the workspace. I is the same - only in this workspace though. Do you have any idea for a workaround for me? Maybe how to find out which page is causing the issue?
Thank you so much for your support 🙏

**Closed as completed** 2024-08-09 09:18 UTC
