### ISSUE TITLE
App icon is not delivered with AppImage on Linux​

### ISSUE THREAD

**Issue by STRRL** [toeverything/AFFiNE#3837] opened 2023-08-19 07:30 UTC
### What happened?

I downloaded the 0.8 beta version from the official website, and I got an AppImage application.

And I noticed the application has NO icon entry in both 

- the .desktop file
- the application Window

<img width="506" alt="image" src="https://github.com/toeverything/AFFiNE/assets/20221408/23fe9168-d45c-4d30-b0c2-95180a0d2388">

<img width="900" alt="image" src="https://github.com/toeverything/AFFiNE/assets/20221408/ca2381d1-2227-41b5-9f23-822b159db7a2">

<img width="314" alt="image" src="https://github.com/toeverything/AFFiNE/assets/20221408/85f1b92f-38fa-4113-89f0-383474b37be9">

### Distribution version

Linux

### Anything else?

I would like to submit a PR, but I am not so familiar with electron application.

If you could give me a direction or potential solution, I am very glad to work on it!

Thanks!

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment] 2023-08-19 17:12
Related code:

https://github.com/toeverything/AFFiNE/blob/e6cd193bf469cdcd9cf62a4dac726cfd498532e5/apps/electron/forge.config.js#L91-L101

**Comment by TheNexter** [comment] 2023-12-31 13:34
I confirm, there is no icon for this package 🫠

Could anyone patch this before the 0.12.0 ? 😅
The default icon is very ugly and the app feel very alpha state without icon at first impression 😅

**Comment by TheNexter** [comment] 2024-01-04 19:01
what is looks like :
![image](https://github.com/toeverything/AFFiNE/assets/17613028/138e9f85-42e1-4506-881a-5d367140cd27)

**Comment by xihale** [comment] 2024-02-24 15:09
I extracted the appimage(`./affine-stable-linux-x64.AppImage --appimage-extract`) and then `cd squashfs-root`.
After that, I tried to search the icon files, and found that all the icon file is the default icon for electron(no matter `squashfs-root/AFFiNE.png` or `squashfs-root/usr/share/icons/hicolor/*`).
So I think the problem is on electron Appimage release setting.

**Comment by pengx17** [comment] 2024-03-21 13:46
fixed in https://github.com/toeverything/AFFiNE/pull/6257

**Closed** 2024-03-22 02:42 UTC
Labels: type:bug, platform:linux
