### ISSUE TITLE
onig.wasm is not packed in AFFiNE

### ISSUE THREAD

**Issue by biaomingzhong** [toeverything/AFFiNE#5608] opened 2024-01-12 12:03 UTC
### What happened?

There are two issues with the Code block: 

1. The text inside the Code block cannot be copied. When attempting to copy the text, it displays 'Copied to clipboard' but the text is not actually copied.

2. The Code block itself cannot be copied at times. A toast message appears stating 'Copied failed …'

<img width="991" alt="CleanShot 2024-01-12 at 19 58 31@2x" src="https://github.com/toeverything/AFFiNE/assets/5178619/73a57474-5f68-4dc0-972e-b7c07ffd08bb">

### Distribution version

macOS ARM 64 (Apple Silicon)

### What browsers are you seeing the problem on if you're using web version?

Other

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by biaomingzhong** [comment] 2024-01-12 12:05
I am using the 0.11.2 version of Desktop App

<img width="278" alt="CleanShot 2024-01-12 at 20 03 59@2x" src="https://github.com/toeverything/AFFiNE/assets/5178619/5453d8eb-f334-4ac4-8be0-3743f6634bcc">

**Comment by fourdim** [comment] 2024-01-12 19:34
Closed by toeverything/blocksuite#5964. An update to AFFiNE 0.11.3 (Already released) will fix this issue.

**Comment by biaomingzhong** [comment] 2024-01-15 02:09
![CleanShot 2024-01-15 at 10 06 44@2x](https://github.com/toeverything/blocksuite/assets/5178619/ade576d5-99c2-4b16-8d9c-70e22302bdfc)

Not working

**Comment by biaomingzhong** [comment] 2024-01-15 02:09
> Closed by toeverything/blocksuite#5964. An update to AFFiNE 0.11.3 (Already released) will fix this issue.

Please take a look

**Comment by fourdim** [comment] 2024-01-15 02:28
Press `crtl/cmd+shift+i` and copy logs to here will help.

**Comment by biaomingzhong** [comment] 2024-01-16 10:17
```
fetch.js:43 
        
        
       GET file://./workspace/2e8b944f-dcc6-4c7d-879f-ac9352fa6318/dist/onig.wasm net::ERR_UNEXPECTED
(anonymous) @ fetch.js:43
A @ index.esm.js:2280
q @ index.esm.js:3139
n @ high-lighter.js:11
_deltaToHigglightHasts @ html.js:690
(anonymous) @ html.js:112
_visit @ base.js:35
walk @ base.js:25
_traverseSnapshot @ html.js:344
fromSliceSnapshot @ html.js:915
_getClipboardItem @ index.js:113
await in _getClipboardItem (async)
(anonymous) @ index.js:91
(anonymous) @ index.js:90
writeToClipboard @ index.js:121
copySlice @ index.js:88
(anonymous) @ code-option.js:37
handleEvent @ lit-html.js:6
o @ helpers.js:90
fetch.js:43 
        
        
       GET file://./workspace/2e8b944f-dcc6-4c7d-879f-ac9352fa6318/themes/nord.json net::ERR_UNEXPECTED
(anonymous) @ fetch.js:43
I @ index.esm.js:2322
N @ index.esm.js:2330
O @ index.esm.js:2345
loadTheme @ index.esm.js:3030
(anonymous) @ index.esm.js:3042
loadThemes @ index.esm.js:3042
q @ index.esm.js:3147
n @ high-lighter.js:11
_deltaToHigglightHasts @ html.js:690
(anonymous) @ html.js:112
_visit @ base.js:35
walk @ base.js:25
_traverseSnapshot @ html.js:344
fromSliceSnapshot @ html.js:915
_getClipboardItem @ index.js:113
await in _getClipboardItem (async)
(anonymous) @ index.js:91
(anonymous) @ index.js:90
writeToClipboard @ index.js:121
copySlice @ index.js:88
(anonymous) @ code-option.js:37
handleEvent @ lit-html.js:6
o @ helpers.js:90
console.js:36 TypeError: Failed to fetch
    at fetch.js:43:28
    at I (index.esm.js:2322:18)
    at N (index.esm.js:2330:29)
    at O (index.esm.js:2345:21)
    at W.loadTheme (index.esm.js:3030:45)
    at index.esm.js:3042:57
    at Array.map (<anonymous>)
    at W.loadThemes (index.esm.js:3042:37)
    at q (index.esm.js:3147:34)
    at n (high-lighter.js:11:26)
    at u._deltaToHigglightHasts (html.js:690:39)
    at c._enter (html.js:112:50)
    at c._visit (base.js:35:28)
    at c.walk (base.js:25:24)
    at u._traverseSnapshot (html.js:344:36)
    at u.fromSliceSnapshot (html.js:915:51)
    at $._getClipboardItem (index.js:113:31)
    at async index.js:91:34
    at async Promise.all (index 1)
    at async index.js:90:17
    at async $.writeToClipboard (index.js:121:23)
    at async $.copySlice (index.js:88:13)
(anonymous) @ console.js:36
(anonymous) @ code-option.js:43
Promise.catch (async)
(anonymous) @ code-option.js:41
handleEvent @ lit-html.js:6
o @ helpers.js:90
fetch.js:43 
        
        
       Uncaught (in promise) TypeError: Failed to fetch
    at fetch.js:43:28
    at A (index.esm.js:2280:23)
    at q (index.esm.js:3139:34)
    at n (high-lighter.js:11:26)
    at u._deltaToHigglightHasts (html.js:690:39)
    at c._enter (html.js:112:50)
    at c._visit (base.js:35:28)
    at c.walk (base.js:25:24)
    at u._traverseSnapshot (html.js:344:36)
    at u.fromSliceSnapshot (html.js:915:51)
    at $._getClipboardItem (index.js:113:31)
    at async index.js:91:34
    at async Promise.all (index 1)
    at async index.js:90:17
    at async $.writeToClipboard (index.js:121:23)
    at async $.copySlice (index.js:88:13)
(anonymous) @ fetch.js:43
A @ index.esm.js:2280
q @ index.esm.js:3139
n @ high-lighter.js:11
_deltaToHigglightHasts @ html.js:690
(anonymous) @ html.js:112
_visit @ base.js:35
walk @ base.js:25
_traverseSnapshot @ html.js:344
fromSliceSnapshot @ html.js:915
_getClipboardItem @ index.js:113
await in _getClipboardItem (async)
q @ index.esm.js:3139
n @ high-lighter.js:11
_deltaToHigglightHasts @ html.js:690
(anonymous) @ html.js:112
_visit @ base.js:35
walk @ base.js:25
_traverseSnapshot @ html.js:344
fromSliceSnapshot @ html.js:915
_getClipboardItem @ index.js:113
await in _getClipboardItem (async)
(anonymous) @ index.js:91
(anonymous) @ index.js:90
writeToClipboard @ index.js:121
copySlice @ index.js:88
(anonymous) @ code-option.js:37
handleEvent @ lit-html.js:6
o @ helpers.js:90
```

**Comment by EYHN** [comment] 2024-01-19 11:53
I can't reproduce it in 0.11.3

**Closed as completed** 2024-02-22 07:53 UTC
Labels: type:bug
