### ISSUE TITLE
Global disable switch for AI

### ISSUE THREAD

**Issue by Tealk** [toeverything/AFFiNE#8989] opened 2024-12-02 17:09 UTC
### Description

An option for the administration to disable AI completely, or that it is hidden if none is configured.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by bfcns** [comment] 2024-12-12 02:10
This is one of the features needed desperately.

**Comment by Tealk** [comment] 2024-12-12 17:24
I saw this in canary v3, but unfortunately it's stuck in a loop so I can't make a screen.

**Comment by missingfile** [comment] 2024-12-30 21:00
Seems like this is a duplicate of #6920

**Comment by Tealk** [comment] 2024-12-31 00:55
Yes sounds like the same

**Closed as completed** 2024-12-31 00:55 UTC
Labels: story
