### ISSUE TITLE
Page mode share cannot slide

### ISSUE THREAD

**Issue by YanxinLu0122** [toeverything/AFFiNE#5260] opened 2023-12-11 09:28 UTC
https://github.com/toeverything/AFFiNE/assets/144991896/caff7c2c-a801-45ca-a1d7-db97d213469c

**Comment by joooye34** [comment] 2023-12-12 07:05
I can't reproduce this issue, pls take a look. @JimmFly

**Comment by JimmFly** [comment] 2023-12-13 09:12
fixed in https://github.com/toeverything/AFFiNE/pull/5263

**Closed as completed by JimmFly** 2023-12-13 09:12 UTC
Labels: type:bug, beta
