### ISSUE TITLE
This ERC was created post-split. Is there a guideline to link to ERCs now?

### ISSUE THREAD

**Issue by cum8197** [toeverything/AFFiNE#7063] opened 2024-05-24 23:23 UTC
This ERC was created post-split. Is there a guideline to link to ERCs now?

_Originally posted by @frangio in https://github.com/ethereum/EIPs/pull/8594#discussion_r1612514416_

_Originally posted by @cum8197 in https://github.com/toeverything/AFFiNE/issues/7062_

**Comment by JimmFly** [comment] 2024-05-27 07:07
This is a duplicate of issue #7062, I will close this one.

**Closed as not planned by JimmFly** 2024-05-27 07:07 UTC
