### ISSUE TITLE
[bug]: all page's section is not responsive (feedback by Abid) 

### ISSUE THREAD

**Issue by Yipei-Operation** [toeverything/AFFiNE#698] opened 2023-01-09 08:03 UTC
### Describe the bug

All page's section is not responsive happening when make my windows portrait mode or side by side with another window

### To Reproduce

1. Go to pathfinder.affine.pro
2. when I make my windows portrait mode or side by side with another window
3. all page's action is not responded

### Screenshots
![window2](https://user-images.githubusercontent.com/79373028/211262940-8aaa17fd-a2bc-499d-9ef2-76bc72089edb.jpg)

### Expected behavior

All actions should be responded as expected.
currently it shown as: [video for window bug.webm](https://user-images.githubusercontent.com/79373028/211263480-d03e4aef-e6e4-482d-bef9-09b8ffa17508.webm)

### Platform

Linux

### Additional context

Feedback by https://github.com/enamulhasanabid

**Comment by QiShaoXuan** [comment] 2023-01-09 08:54
The issue may be caused by the low screen resolution，we will fix soon

**Comment by tzhangchi** [comment] 2023-06-06 03:32
The issue had been fixed in the latest https://github.com/toeverything/AFFiNE/releases

**Closed by tzhangchi** 2023-06-06 03:32 UTC
Labels: bug
