### ISSUE TITLE
(0.9.0-​canary.11) No titlebar on Windows, blank space on bottom

### ISSUE THREAD

**Issue by spusuf** [toeverything/AFFiNE#4296] opened 2023-09-10 23:40 UTC
### What happened?

There is no menu bar  (also called title bar or OS panel ) on Windows in the latest canary release, have not checked previous releases. The sidebar is leaving space for it, and as a result the side menu does not reach the bottom of the application and leaves a blank space (shown in image 2). There is no GUI way to move the window, nor to close it (resizing the edges works and alt + f4 works).

Images included: 0.8 beta left, 0.9 canary11 right.

![image](https://github.com/toeverything/AFFiNE/assets/86286368/7e1759a5-f996-401a-857c-1535c60f0329)

![image](https://github.com/toeverything/AFFiNE/assets/86286368/98502125-9058-4e2a-be87-f758cfbaf9f9)

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pengx17** [comment] 2023-09-11 01:46
This is indeed strange. I will take a look

**Comment by pengx17** [comment] 2023-09-12 05:52
> There is no menu bar (also called title bar or OS panel ) on Windows in the latest canary release
This is by design. We did not find a good way to fit the native windows menu bar into our design system.

Regarding moving and closing the app window, you should be able to it with the area as shown in the red rectangle (also is available in the image you captured for 0.8 beta). If you cannot see it, I guess there is a bug that pushes the whole page a upwards bit thus the header area is out of sight. I am not sure why this happens yet.
![image](https://github.com/toeverything/AFFiNE/assets/584378/67ef25bc-3cb2-4e35-9b41-56148667a869)

**Closed** 2023-09-12 07:02 UTC
Labels: type:bug
