### ISSUE TITLE
Linux system can not download 0.8.0 appimage

### ISSUE THREAD

**Issue by YanxinLu0122** [toeverything/AFFiNE#4500] opened 2023-09-26 02:25 UTC
version of Linux:

![Image](https://github.com/toeverything/AFFiNE/assets/144991896/8a64f6b7-7fd5-4418-acfe-c1dca2559a20)

**Comment by pengx17** [comment] 2023-09-26 03:04
duplicate of https://github.com/toeverything/AFFiNE/issues/4443

**Closed** 2024-02-13 07:42 UTC
Labels: type:bug, blocked, app:electron
